spring.application.name=Backen-Gateway


#Server port
server.port=8094


#Eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eurkea.clinet.service-url.defalutZone=http://localhost:8761/eureka

#beckn configuartion
beckn.bpp.id=api.c3tp.in
beckn.bpp.uri=https://api.c3tp.in